---
title: "cleaning"
author: "Merly Klaas"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r, warning=FALSE, message=FALSE}
pacman::p_load(rio, here, tidyverse, lattice,lme4,performance, maps, mapdata, ggthemes, ggrepel, rgdal,raster, viridis,sf)
```



```{r}
sc1 <- import(here("data", "school-odd22:23.xlsx"))
sc2 <-import(here("data", "school-even22:23.xlsx"))
tch1 <- import(here("data", "teacher-odd22:23.xlsx"))
tch2 <- import(here("data", "teacher-even22:23.xlsx"))
coh1 <- import(here("data", "cohort-od22:23.xlsx"))
coh2 <- import(here("data", "cohort-even22:23.xlsx"))
stu1 <- import(here("data", "student-odd22:23.xlsx"))
stu1$totstutkm<-as.numeric(stu1$totstutkm)
stu2 <- import(here("data", "student-even22:23.xlsx"))
name <- import(here("data", "name.xlsx"))
name$id <- as.character(name$id)
```


Join data teacher, students, cohorts data for year 22/23
```{r}
sc<- full_join(sc1, sc2) 
tch <- full_join(tch1, tch2)
stu <- full_join(stu1, stu2)
coh <- full_join(coh1, coh2)

bps <- left_join(sc, tch) %>% 
  left_join(stu) %>% 
  left_join(coh) 

```

```{r}
idn_shape <- rgdal::readOGR(dsn=path.expand("/Users/merlyklaas/Downloads/idn_adm_bps_20200401_shp/idn_admbnda_adm1_bps_20200401.shp"), layer = "idn_admbnda_adm1_bps_20200401")

idn_shape_df <- fortify(idn_shape)
head(idn_shape_df)

idn <- left_join(idn_shape_df, name)
```

```{r}
str(idn_shape_df)
str(name)

idn <- left_join(idn_shape_df, name)

dat <- left_join(idn, bps)
```
Try out using number of kindergarten per province

```{r}
dat %>% 
  filter(term == 1) %>% 
  ggplot(aes(x = long, y = lat, group = group)) +
  coord_fixed(1.3) + 
  geom_polygon(aes(x=long,y=lat, group=group, fill=totkin), color='black') +
  scale_fill_viridis()+
  geom_polygon(color = "black", fill = NA) +
  theme_bw()
```




```{r}
global <- map_data("world") #World longitude and latitude data 

View(global) #view the data and notice the column of long, lat, and group

gg1 <- ggplot() + 
  geom_polygon(data = global, aes(x=long, y = lat, group = group), 
               fill = "gray85", color = "gray80") + 
  coord_fixed(1.3) 
#you can change the "fill" (fill color) and the "color" (line color)

print(gg1) #show the plot
```

```{r}
Indo<-gg1 + xlim(94,142) + ylim(-11,7)

#try to change the values of xlim and ylim and see what you get

print(Indo)   
```

